### ISSUE TITLE
Feature: namespace (netns) support

### ISSUE THREAD

**Issue by teedu** [liske/ifstate#9]
It would be nice if ifstate had support for namespaces

**Comment by liske** [comment]
this is already on my wishlist/todo :-)

**Comment by liske** [comment]
ToDo:

- [x] extend JSON schema to support `namespaces:`
- [x] create/destroy namespaces
- [x] extend logging to be namespace aware
- [x] do not use a global `IPRoute` instance, use `NetNS` drop-ins for namespaces
- [x] basic link/addresses/neighbours/routing support
- [ ] `sysctl` in namespaces
- [ ] `businfo` in namespaces
- [ ] `permaddr`in namespaces
- [ ] *master*/*link* relations between namespaces
- [ ] move physical links between namespaces
- [ ] `ethtool` in namespaces
- [ ]
